In [1]:
def ordenar_chamados(path_excel='chamados.xlsx'):
    import pandas as pd

    try:
        chamados = pd.read_excel(path_excel)

        chamados['data_abertura'] = pd.to_datetime(chamados['data_abertura'])

        chamados_ordenados = chamados.sort_values(
            by=['prioridade', 'data_abertura', 'cliente'],
            ascending=[True, True, True]
        ).reset_index(drop=True)

        # Salvar o DataFrame ordenado de volta no Excel
        chamados_ordenados.to_excel(path_excel, index=False)

        return chamados_ordenados

    except FileNotFoundError:
        print(f"O arquivo {path_excel} não foi encontrado.")
        return pd.DataFrame()


chamados_ordenados = ordenar_chamados()

display(chamados_ordenados)

,id,cliente,maquina,tipo_manutencao,tempo_necessario,prioridade,data_abertura
0,31,cliente_1,maquina_6,manutencao_corretiva,3,prioridade_1,2025-01-07
1,113,cliente_4,maquina_4,manutencao_preventiva,2,prioridade_1,2025-01-08
2,84,cliente_8,maquina_5,manutencao_preventiva,2,prioridade_1,2025-01-08
3,149,cliente_4,maquina_6,manutencao_corretiva,3,prioridade_1,2025-01-10
4,180,cliente_20,maquina_9,avaliacao_do_equipamento,1,prioridade_1,2025-01-13
...,...,...,...,...,...,...,...
195,114,cliente_29,maquina_6,manutencao_corretiva,3,prioridade_3,2025-05-20
196,142,cliente_30,maquina_4,manutencao_corretiva,3,prioridade_3,2025-05-21
197,54,cliente_14,maquina_5,avaliacao_do_equipamento,1,prioridade_3,2025-05-23
198,129,cliente_13,maquina_6,manutencao_preventiva,2,prioridade_3,2025-05-24
199,196,cliente_15,maquina_8,manutencao_corretiva,3,prioridade_3,2025-05-29