In [1]:
import pandas as pd
from datetime import datetime, timedelta

def criar_agenda_tecnicos(
    arquivo_tecnicos='tecnicos.xlsx',
    data_inicio='2025-01-01',
    data_fim='2025-01-07',
    path_saida='agenda.xlsx'
):
    # LÃª os tÃ©cnicos da aba ativa
    df_tecnicos = pd.read_excel(arquivo_tecnicos)
    tecnicos = df_tecnicos['tecnicos'].tolist()

    # GeraÃ§Ã£o de datas
    inicio = pd.to_datetime(data_inicio)
    fim = pd.to_datetime(data_fim)
    dias = pd.date_range(start=inicio, end=fim)

    # Faixas de horÃ¡rio vÃ¡lidas (sem horÃ¡rio de almoÃ§o)
    horarios = [
        "08:00", "09:00", "10:00", "11:00",
        "13:00", "14:00", "15:00", "16:00", "17:00"
    ]

    # Estrutura das colunas (com status_agenda antes de agenda_efetivada)
    colunas = [
        'dia_da_semana', 'data', 'horario', 'status_agenda', 'agenda_efetivada',
        'id', 'cliente', 'maquina', 'tipo_manutencao',
        'tempo_necessario', 'prioridade', 'data_abertura'
    ]

    agendas_tecnicos = {}

    # Criar arquivo com uma aba por tÃ©cnico
    with pd.ExcelWriter(path_saida, engine='openpyxl') as writer:
        for tecnico in tecnicos:
            registros = []
            for dia in dias:
                dia_str = dia.strftime('%Y-%m-%d')
                semana = dia.strftime('%A')  # Nome do dia da semana em inglÃªs

                # Verifica se Ã© sÃ¡bado (Saturday) ou domingo (Sunday)
                status = 'bloqueada' if semana in ['Saturday', 'Sunday'] else 'liberada'

                for hora in horarios:
                    registros.append({
                        'dia_da_semana': semana,
                        'data': dia_str,
                        'horario': hora,
                        'status_agenda': status,
                        'agenda_efetivada': '',
                        'id': '',
                        'cliente': '',
                        'maquina': '',
                        'tipo_manutencao': '',
                        'tempo_necessario': '',
                        'prioridade': '',
                        'data_abertura': ''
                    })

            df_agenda = pd.DataFrame(registros, columns=colunas)
            df_agenda.to_excel(writer, sheet_name=tecnico, index=False)
            agendas_tecnicos[tecnico] = df_agenda

    print(f"Arquivo '{path_saida}' criado com sucesso.")
    return agendas_tecnicos

agendas = criar_agenda_tecnicos('tecnicos.xlsx', data_inicio='2025-01-01', data_fim='2026-12-31')

for tecnico, agenda in agendas.items():
    print(f"\nAgenda de {tecnico}")
    display(agenda)

agendas = criar_agenda_tecnicos('tecnicos.xlsx', data_inicio='2025-01-01', data_fim='2026-12-31')

for tecnico, agenda in agendas.items():
    print(f"\nAgenda de {tecnico}")
    display(agenda)

Arquivo 'agenda.xlsx' criado com sucesso.

Agenda de tecnico_1

,dia_da_semana,data,horario,status_agenda,agenda_efetivada,id,cliente,maquina,tipo_manutencao,tempo_necessario,prioridade,data_abertura
0,Wednesday,2025-01-01,08:00,liberada,,,,,,,,
1,Wednesday,2025-01-01,09:00,liberada,,,,,,,,
2,Wednesday,2025-01-01,10:00,liberada,,,,,,,,
3,Wednesday,2025-01-01,11:00,liberada,,,,,,,,
4,Wednesday,2025-01-01,13:00,liberada,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
6565,Thursday,2026-12-31,13:00,liberada,,,,,,,,
6566,Thursday,2026-12-31,14:00,liberada,,,,,,,,
6567,Thursday,2026-12-31,15:00,liberada,,,,,,,,
6568,Thursday,2026-12-31,16:00,liberada,,,,,,,,
6569,Thursday,2026-12-31,17:00,liberada,,,,,,,,

Agenda de tecnico_2

,dia_da_semana,data,horario,status_agenda,agenda_efetivada,id,cliente,maquina,tipo_manutencao,tempo_necessario,prioridade,data_abertura
0,Wednesday,2025-01-01,08:00,liberada,,,,,,,,
1,Wednesday,2025-01-01,09:00,liberada,,,,,,,,
2,Wednesday,2025-01-01,10:00,liberada,,,,,,,,
3,Wednesday,2025-01-01,11:00,liberada,,,,,,,,
4,Wednesday,2025-01-01,13:00,liberada,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
6565,Thursday,2026-12-31,13:00,liberada,,,,,,,,
6566,Thursday,2026-12-31,14:00,liberada,,,,,,,,
6567,Thursday,2026-12-31,15:00,liberada,,,,,,,,
6568,Thursday,2026-12-31,16:00,liberada,,,,,,,,
6569,Thursday,2026-12-31,17:00,liberada,,,,,,,,

Agenda de tecnico_3

,dia_da_semana,data,horario,status_agenda,agenda_efetivada,id,cliente,maquina,tipo_manutencao,tempo_necessario,prioridade,data_abertura
0,Wednesday,2025-01-01,08:00,liberada,,,,,,,,
1,Wednesday,2025-01-01,09:00,liberada,,,,,,,,
2,Wednesday,2025-01-01,10:00,liberada,,,,,,,,
3,Wednesday,2025-01-01,11:00,liberada,,,,,,,,
4,Wednesday,2025-01-01,13:00,liberada,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
6565,Thursday,2026-12-31,13:00,liberada,,,,,,,,
6566,Thursday,2026-12-31,14:00,liberada,,,,,,,,
6567,Thursday,2026-12-31,15:00,liberada,,,,,,,,
6568,Thursday,2026-12-31,16:00,liberada,,,,,,,,
6569,Thursday,2026-12-31,17:00,liberada,,,,,,,,

Agenda de tecnico_4

,dia_da_semana,data,horario,status_agenda,agenda_efetivada,id,cliente,maquina,tipo_manutencao,tempo_necessario,prioridade,data_abertura
0,Wednesday,2025-01-01,08:00,liberada,,,,,,,,
1,Wednesday,2025-01-01,09:00,liberada,,,,,,,,
2,Wednesday,2025-01-01,10:00,liberada,,,,,,,,
3,Wednesday,2025-01-01,11:00,liberada,,,,,,,,
4,Wednesday,2025-01-01,13:00,liberada,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
6565,Thursday,2026-12-31,13:00,liberada,,,,,,,,
6566,Thursday,2026-12-31,14:00,liberada,,,,,,,,
6567,Thursday,2026-12-31,15:00,liberada,,,,,,,,
6568,Thursday,2026-12-31,16:00,liberada,,,,,,,,
6569,Thursday,2026-12-31,17:00,liberada,,,,,,,,

Agenda de tecnico_5

,dia_da_semana,data,horario,status_agenda,agenda_efetivada,id,cliente,maquina,tipo_manutencao,tempo_necessario,prioridade,data_abertura
0,Wednesday,2025-01-01,08:00,liberada,,,,,,,,
1,Wednesday,2025-01-01,09:00,liberada,,,,,,,,
2,Wednesday,2025-01-01,10:00,liberada,,,,,,,,
3,Wednesday,2025-01-01,11:00,liberada,,,,,,,,
4,Wednesday,2025-01-01,13:00,liberada,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
6565,Thursday,2026-12-31,13:00,liberada,,,,,,,,
6566,Thursday,2026-12-31,14:00,liberada,,,,,,,,
6567,Thursday,2026-12-31,15:00,liberada,,,,,,,,
6568,Thursday,2026-12-31,16:00,liberada,,,,,,,,
6569,Thursday,2026-12-31,17:00,liberada,,,,,,,,

Arquivo 'agenda.xlsx' criado com sucesso.

Agenda de tecnico_1

,dia_da_semana,data,horario,status_agenda,agenda_efetivada,id,cliente,maquina,tipo_manutencao,tempo_necessario,prioridade,data_abertura
0,Wednesday,2025-01-01,08:00,liberada,,,,,,,,
1,Wednesday,2025-01-01,09:00,liberada,,,,,,,,
2,Wednesday,2025-01-01,10:00,liberada,,,,,,,,
3,Wednesday,2025-01-01,11:00,liberada,,,,,,,,
4,Wednesday,2025-01-01,13:00,liberada,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
6565,Thursday,2026-12-31,13:00,liberada,,,,,,,,
6566,Thursday,2026-12-31,14:00,liberada,,,,,,,,
6567,Thursday,2026-12-31,15:00,liberada,,,,,,,,
6568,Thursday,2026-12-31,16:00,liberada,,,,,,,,
6569,Thursday,2026-12-31,17:00,liberada,,,,,,,,

Agenda de tecnico_2

,dia_da_semana,data,horario,status_agenda,agenda_efetivada,id,cliente,maquina,tipo_manutencao,tempo_necessario,prioridade,data_abertura
0,Wednesday,2025-01-01,08:00,liberada,,,,,,,,
1,Wednesday,2025-01-01,09:00,liberada,,,,,,,,
2,Wednesday,2025-01-01,10:00,liberada,,,,,,,,
3,Wednesday,2025-01-01,11:00,liberada,,,,,,,,
4,Wednesday,2025-01-01,13:00,liberada,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
6565,Thursday,2026-12-31,13:00,liberada,,,,,,,,
6566,Thursday,2026-12-31,14:00,liberada,,,,,,,,
6567,Thursday,2026-12-31,15:00,liberada,,,,,,,,
6568,Thursday,2026-12-31,16:00,liberada,,,,,,,,
6569,Thursday,2026-12-31,17:00,liberada,,,,,,,,

Agenda de tecnico_3

,dia_da_semana,data,horario,status_agenda,agenda_efetivada,id,cliente,maquina,tipo_manutencao,tempo_necessario,prioridade,data_abertura
0,Wednesday,2025-01-01,08:00,liberada,,,,,,,,
1,Wednesday,2025-01-01,09:00,liberada,,,,,,,,
2,Wednesday,2025-01-01,10:00,liberada,,,,,,,,
3,Wednesday,2025-01-01,11:00,liberada,,,,,,,,
4,Wednesday,2025-01-01,13:00,liberada,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
6565,Thursday,2026-12-31,13:00,liberada,,,,,,,,
6566,Thursday,2026-12-31,14:00,liberada,,,,,,,,
6567,Thursday,2026-12-31,15:00,liberada,,,,,,,,
6568,Thursday,2026-12-31,16:00,liberada,,,,,,,,
6569,Thursday,2026-12-31,17:00,liberada,,,,,,,,

Agenda de tecnico_4

,dia_da_semana,data,horario,status_agenda,agenda_efetivada,id,cliente,maquina,tipo_manutencao,tempo_necessario,prioridade,data_abertura
0,Wednesday,2025-01-01,08:00,liberada,,,,,,,,
1,Wednesday,2025-01-01,09:00,liberada,,,,,,,,
2,Wednesday,2025-01-01,10:00,liberada,,,,,,,,
3,Wednesday,2025-01-01,11:00,liberada,,,,,,,,
4,Wednesday,2025-01-01,13:00,liberada,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
6565,Thursday,2026-12-31,13:00,liberada,,,,,,,,
6566,Thursday,2026-12-31,14:00,liberada,,,,,,,,
6567,Thursday,2026-12-31,15:00,liberada,,,,,,,,
6568,Thursday,2026-12-31,16:00,liberada,,,,,,,,
6569,Thursday,2026-12-31,17:00,liberada,,,,,,,,

Agenda de tecnico_5

,dia_da_semana,data,horario,status_agenda,agenda_efetivada,id,cliente,maquina,tipo_manutencao,tempo_necessario,prioridade,data_abertura
0,Wednesday,2025-01-01,08:00,liberada,,,,,,,,
1,Wednesday,2025-01-01,09:00,liberada,,,,,,,,
2,Wednesday,2025-01-01,10:00,liberada,,,,,,,,
3,Wednesday,2025-01-01,11:00,liberada,,,,,,,,
4,Wednesday,2025-01-01,13:00,liberada,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...
6565,Thursday,2026-12-31,13:00,liberada,,,,,,,,
6566,Thursday,2026-12-31,14:00,liberada,,,,,,,,
6567,Thursday,2026-12-31,15:00,liberada,,,,,,,,
6568,Thursday,2026-12-31,16:00,liberada,,,,,,,,
6569,Thursday,2026-12-31,17:00,liberada,,,,,,,,